language: android
android:
  components:
    - android-8
jdk:
  - oraclejdk8
  - oraclejdk7
sudo: false
cache:
  directories:
  - $HOME/.m2

install: gradle assemble
script: gradle check
after_success:
  gradle jacocoRootReport coveralls
